name: Build and Commit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          if git commit -m "Update build" ; then
            git push origin HEAD:main
          fi
