name: Build and Commit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Remover as linhas npm
      - run: git config user.name github-actions
      - run: git config user.email github-actions[bot]@users.noreply.github.com
      - run: git add .
      - run: |
          if git commit -m "Update build" ; then
            git push origin HEAD:main
          fi
